// starmap-data.js — destination catalog lifted from js/bodies.js, js/starmap.js, js/deepspace.js
// short: lowercase one-liner (starmap.js BODY_META/CRAFT_META style)
// desc:  full description (bodies.js / deepspace.js)
// au:    heliocentric distance used for spatial layout (landmarks use the game's scaled dist)
// ly:    real light-year distance for display (landmarks only)
export const DESTINATIONS = [
  { name:'SUN', type:'star', kind:'g-type star', color:'#ffdd66', au:0.02, angle:0, phi:0,
    short:'our star \u2014 where all this begins',
    desc:'Our star. 4.6 billion years old, 1.4 million km diameter. 99.86% of the solar system mass.' },
  { name:'MERCURY', type:'planet', kind:'planet', color:'#b0a090', au:0.39, angle:0.9, phi:0,
    short:'the smallest planet, scarred by craters',
    desc:'Smallest planet. Cratered surface, extreme temperature swings of 600\u00B0C.' },
  { name:'VENUS', type:'planet', kind:'planet', color:'#d9b56a', au:0.72, angle:2.2, phi:0,
    short:'shrouded in permanent clouds',
    desc:'Hottest planet at 465\u00B0C. Thick sulphuric acid cloud cover.' },
  { name:'EARTH', type:'planet', kind:'planet', color:'#4a9cff', au:1.0, angle:3.7, phi:0, ship:true,
    short:'our pale blue dot',
    desc:'Our home. 71% ocean. City lights visible on the dark side.' },
  { name:'MOON', type:'moon', kind:'moon', parent:'EARTH', color:'#cccccc', shipKm:384400,
    short:'earth\u2019s tidally-locked companion',
    desc:"Earth's only natural satellite. Tidally locked, 384,400 km away." },
  { name:'MARS', type:'planet', kind:'planet', color:'#c15a3b', au:1.52, angle:5.1, phi:0,
    short:'the red planet',
    desc:'The Red Planet. Valles Marineris \u2014 4,000 km canyon. Polar ice caps.' },
  { name:'PHOBOS', type:'moon', kind:'moon', parent:'MARS', color:'#9a8a7a',
    short:'doomed moon, spiralling ever closer',
    desc:'Tiny, irregular moon. Orbits so close it will break apart in 50M years.' },
  { name:'DEIMOS', type:'moon', kind:'moon', parent:'MARS', color:'#9a8a7a',
    short:'only 12 km across, slowly drifting away',
    desc:'Mars\u2019s smaller moon. Only 12 km across. Slowly drifting away.' },
  { name:'CERES', type:'dwarf', kind:'dwarf planet', color:'#888888', au:2.77, angle:0.5, phi:0,
    short:'largest body in the asteroid belt',
    desc:'Largest object in the asteroid belt. Dwarf planet, 940 km diameter.' },
  { name:'JUPITER', type:'planet', kind:'planet', color:'#d9a566', au:5.2, angle:1.6, phi:0,
    short:'gas giant king of the solar system',
    desc:'Largest planet. Great Red Spot \u2014 a storm for centuries.' },
  { name:'IO', type:'moon', kind:'moon', parent:'JUPITER', color:'#e8d060',
    short:'four hundred volcanoes, always burning',
    desc:'Most volcanically active body in the solar system. 400+ active volcanoes.' },
  { name:'EUROPA', type:'moon', kind:'moon', parent:'JUPITER', color:'#d8c8b0',
    short:'an ocean sleeps beneath the ice',
    desc:'Subsurface ocean beneath ice crust. Prime candidate for extraterrestrial life.' },
  { name:'GANYMEDE', type:'moon', kind:'moon', parent:'JUPITER', color:'#b0a898',
    short:'the largest moon in the solar system',
    desc:'Largest moon in the solar system. Bigger than Mercury. Has its own magnetic field.' },
  { name:'CALLISTO', type:'moon', kind:'moon', parent:'JUPITER', color:'#8a8478',
    short:'four billion years of impacts',
    desc:'Most heavily cratered object in the solar system. 4.5 billion years of impacts.' },
  { name:'SATURN', type:'planet', kind:'planet', color:'#e8cc88', au:9.58, angle:2.9, phi:0,
    short:'crowned by an icy ring system',
    desc:'Ring system spans 280,000 km yet averages ~10m thick.' },
  { name:'TITAN', type:'moon', kind:'moon', parent:'SATURN', color:'#d8a850',
    short:'methane rain and hidden seas',
    desc:'Only moon with a dense atmosphere. Methane lakes and rain. Larger than Mercury.' },
  { name:'ENCELADUS', type:'moon', kind:'moon', parent:'SATURN', color:'#e8f0f8',
    short:'geysers of ice from a buried ocean',
    desc:'Geysers of water ice erupt from the south pole. Subsurface ocean confirmed.' },
  { name:'MIMAS', type:'moon', kind:'moon', parent:'SATURN', color:'#b8b8b8',
    short:'the death star moon',
    desc:'Herschel crater makes it look like the Death Star. Only 396 km across.' },
  { name:'URANUS', type:'planet', kind:'planet', color:'#88cce0', au:19.2, angle:4.3, phi:0,
    short:'tilted on its side \u2014 an ice giant',
    desc:'Ice giant tilted 98\u00B0. Rotates on its side.' },
  { name:'TITANIA', type:'moon', kind:'moon', parent:'URANUS', color:'#a8b0b8',
    short:'icy canyons in permanent twilight',
    desc:'Largest moon of Uranus. Icy surface with massive canyons.' },
  { name:'OBERON', type:'moon', kind:'moon', parent:'URANUS', color:'#888c94',
    short:'a dark, ancient, cratered world',
    desc:'Outermost major moon of Uranus. Dark, cratered, ancient surface.' },
  { name:'NEPTUNE', type:'planet', kind:'planet', color:'#4466d0', au:30.1, angle:5.6, phi:0,
    short:'the farthest ice giant, wind-torn',
    desc:'Windiest world. Storms reach 2,100 km/h. 165-year orbit.' },
  { name:'TRITON', type:'moon', kind:'moon', parent:'NEPTUNE', color:'#c8d8e0',
    short:'captured wanderer, orbiting backwards',
    desc:'Captured Kuiper Belt object. Orbits backwards. Nitrogen geysers.' },
  { name:'PLUTO', type:'dwarf', kind:'dwarf planet', color:'#b0a090', au:39.5, angle:0.2, phi:0.10,
    short:'distant dwarf, heart of ice',
    desc:'Dwarf planet with a heart-shaped nitrogen glacier. 248-year orbit.' },
  { name:'ERIS', type:'dwarf', kind:'dwarf planet', color:'#ccddee', au:68, angle:2.6, phi:-0.18,
    short:'icy dwarf planet at the edge',
    desc:'Most massive dwarf planet. Icy surface, 96 AU aphelion.' },
  // ── Spacecraft ──
  { name:'ISS', type:'craft', kind:'space station', parent:'EARTH', color:'#ffffff', shipKm:420,
    short:'our home in low earth orbit',
    desc:'International Space Station. 420 km altitude. Continuously crewed since 2000. Visible from Earth with naked eye.' },
  { name:'HUBBLE', type:'craft', kind:'space telescope', parent:'EARTH', color:'#ccddff', shipKm:540,
    short:'deep-field pioneer, since 1990',
    desc:'Hubble Space Telescope. 540 km altitude. Launched 1990. Revolutionized astronomy with deep field images.' },
  { name:'JWST', type:'craft', kind:'space telescope', parent:'EARTH', color:'#ffdd66', shipKm:1500000,
    short:'infrared eye on the early universe',
    desc:'James Webb Space Telescope at Sun-Earth L2 point. 6.5m gold mirror. Seeing the first galaxies formed after the Big Bang.' },
  { name:'NEW HORIZONS', type:'craft', kind:'deep-space probe', color:'#ddddff', au:61, angle:0.25, phi:0.05,
    short:'first visit to pluto, 2015',
    desc:'First to fly by Pluto (2015). Revealed a heart-shaped nitrogen glacier. Now exploring the Kuiper Belt.' },
  { name:'VOYAGER 1', type:'craft', kind:'deep-space probe', color:'#ffeedd', au:163, angle:3.0, phi:0.5,
    short:'humanity\u2019s furthest emissary, 1977',
    desc:'Launched 1977. Farthest human-made object at 24.4 billion km. First to enter interstellar space (2012). Still transmitting.' },
  { name:'VOYAGER 2', type:'craft', kind:'deep-space probe', color:'#ffeedd', au:135, angle:4.6, phi:-0.4,
    short:'only spacecraft to visit all four gas giants',
    desc:'Launched 1977. Only spacecraft to visit all four gas giants. Entered interstellar space 2018. Twin of Voyager 1.' },
  // ── Landmarks (deepspace.js LANDMARK_DEFS; au = game-scaled dist, ly = real distance) ──
  { name:'PILLARS OF CREATION', type:'landmark', tier:'interstellar', kind:'star-forming nebula', color:'#ffaa44', au:4000, angle:1.8, phi:0.4, ly:6500,
    short:'towering columns of starbirth in the eagle nebula',
    desc:'Towering columns of interstellar gas in the Eagle Nebula, 6,500 light-years distant. Star-forming region immortalized by Hubble.' },
  { name:'CRAB NEBULA', type:'landmark', tier:'interstellar', kind:'supernova remnant', color:'#ff6644', au:5000, angle:3.5, phi:-0.3, ly:6500,
    short:'the shattered heart of the 1054 supernova',
    desc:'Supernova remnant from 1054 AD. A pulsar at its heart spins 30 times per second, powering the expanding filaments.' },
  { name:'UY SCUTI', type:'landmark', tier:'interstellar', kind:'red hypergiant', color:'#ff4422', au:6000, angle:0.8, phi:0.15, ly:9500,
    short:'a star that would swallow jupiter\u2019s orbit',
    desc:'One of the largest known stars. If placed at the Sun, its surface would engulf Jupiter\u2019s orbit.' },
  { name:'CARINA NEBULA', type:'landmark', tier:'interstellar', kind:'star-forming nebula', color:'#ff8855', au:5500, angle:4.8, phi:0.7, ly:8500,
    short:'a stellar nursery four times the size of orion',
    desc:'A vast star-forming region four times larger than the Orion Nebula. Home to Eta Carinae and the Keyhole Nebula.' },
  { name:'RING NEBULA', type:'landmark', tier:'interstellar', kind:'planetary nebula', color:'#44aaff', au:3500, angle:2.5, phi:-0.6, ly:2300,
    short:'the glowing shell of a dying sun',
    desc:'A planetary nebula in Lyra, the glowing shell of gas expelled by a dying Sun-like star 2,300 light-years away.' },
  { name:'HORSEHEAD NEBULA', type:'landmark', tier:'interstellar', kind:'dark nebula', color:'#cc4422', au:4500, angle:5.5, phi:-0.15, ly:1375,
    short:'a silhouette of dust against glowing hydrogen',
    desc:'An iconic dark nebula in Orion, its silhouette shaped by dense dust blocking the glow of emission nebula IC 434.' },
  { name:'ETA CARINAE', type:'landmark', tier:'interstellar', kind:'binary star system', color:'#ffcc33', au:5800, angle:1.2, phi:0.85, ly:7500,
    short:'a massive star on the brink of supernova',
    desc:'A massive binary star system on the brink of supernova. Its Great Eruption in 1843 briefly made it the second-brightest star.' },
  { name:'MAGNETAR', type:'landmark', tier:'interstellar', kind:'magnetar', color:'#cc66ff', au:3000, angle:0.3, phi:-0.9, ly:13000,
    short:'a neutron star with an impossible magnetic field',
    desc:'A neutron star with a magnetic field a quadrillion times stronger than Earth\u2019s. Occasional starquakes release enormous gamma-ray bursts.' },
  { name:'SAGITTARIUS A*', type:'landmark', tier:'intergalactic', kind:'supermassive black hole', color:'#ff8800', au:8000, angle:4.0, phi:-0.2, ly:26000,
    short:'four million suns warping spacetime',
    desc:'The supermassive black hole at the center of the Milky Way. Four million solar masses warping spacetime.' },
  { name:'ANDROMEDA GALAXY', type:'landmark', tier:'intergalactic', kind:'spiral galaxy', color:'#8899dd', au:12000, angle:5.2, phi:0.5, ly:2500000,
    short:'a trillion stars, inbound at 110 km/s',
    desc:'2.5 million light-years away with one trillion stars. Approaching us at 110 km/s for a collision in 4.5 billion years.' },
  { name:'SOMBRERO GALAXY', type:'landmark', tier:'intergalactic', kind:'spiral galaxy', color:'#ddaa66', au:14000, angle:2.0, phi:-0.7, ly:31000000,
    short:'a bright nucleus wrapped in a dust lane',
    desc:'A striking spiral galaxy with a bright nucleus and prominent dust lane, 31 million light-years away in Virgo.' },
  { name:'BOOTES VOID', type:'landmark', tier:'intergalactic', kind:'supervoid', color:'#33506e', au:18000, angle:3.2, phi:0.3, ly:700000000,
    short:'one of the emptiest places in the universe',
    desc:'A supervoid 330 million light-years across containing almost no galaxies. One of the emptiest regions in the observable universe.' },
];

// Section grouping mirrors starmap.js buildList()
export const SECTIONS = [
  { title:'\u2605 start here', featured:true, names:['EARTH','SUN','SATURN','JUPITER'] },
  { title:'planets', names:['SUN','MERCURY','VENUS','EARTH','MARS','JUPITER','SATURN','URANUS','NEPTUNE','PLUTO'] },
  { title:'dwarf planets', names:['CERES','ERIS'] },
  { title:'moons', names:['MOON','PHOBOS','DEIMOS','IO','EUROPA','GANYMEDE','CALLISTO','TITAN','ENCELADUS','MIMAS','TITANIA','OBERON','TRITON'] },
  { title:'spacecraft', names:['ISS','HUBBLE','JWST','NEW HORIZONS','VOYAGER 1','VOYAGER 2'] },
  { title:'nebulae & stars', names:['PILLARS OF CREATION','CRAB NEBULA','UY SCUTI','CARINA NEBULA','RING NEBULA','HORSEHEAD NEBULA','ETA CARINAE','MAGNETAR'] },
  { title:'galaxies & voids', names:['SAGITTARIUS A*','ANDROMEDA GALAXY','SOMBRERO GALAXY','BOOTES VOID'] },
];
